Repository whatever-mentoring/juitcy-server, pull requests merged in 2023-09, with the labels that each got.

#2 [feature/1-setting] Base 파일 추가
  src/main/java/com/ewhatever/qna/answer/entity/Answer.java
  src/main/java/com/ewhatever/qna/comment/entity/Comment.java
  src/main/java/com/ewhatever/qna/common/Base/BaseEntity.java
  src/main/java/com/ewhatever/qna/common/Base/BaseException.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponse.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/notification/entity/Notification.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
  src/main/java/com/ewhatever/qna/scrap/entity/Scrap.java
  src/main/java/com/ewhatever/qna/user/entity/User.java
Labels: infra

#7 [feature/3-getPosts] 주씨글 목록 조회 API
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/common/enums/Category.java
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/dto/GetPostsRes.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/scrap/dto/ScrapResponse.java
  src/main/java/com/ewhatever/qna/scrap/entity/Scrap.java
  src/main/java/com/ewhatever/qna/scrap/repository/ScrapRepository.java
  src/main/java/com/ewhatever/qna/scrap/service/ScrapService.java
Labels: ✨ feature

#8 [feature/6-postAnswer] 질문 등록 API
  src/main/java/com/ewhatever/qna/answer/controller/AnswerController.java
  src/main/java/com/ewhatever/qna/answer/dto/PostAnswerReq.java
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/common/Constant.java
  src/main/java/com/ewhatever/qna/user/repository/UserRepository.java
Labels: ✨ feature

#9 [feature/4-getMyPage] 마이페이지 조회 API
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/comment/repository/CommentRepository.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/common/config/GlobalExceptionHandler.java
  src/main/java/com/ewhatever/qna/common/enums/Role.java
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/scrap/entity/Scrap.java
  src/main/java/com/ewhatever/qna/scrap/repository/ScrapRepository.java
  src/main/java/com/ewhatever/qna/user/controller/UserController.java
  src/main/java/com/ewhatever/qna/user/dto/GetCommentResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetJunyProfileResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetJunyQuestionResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetScrapResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyAnswerResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyProfileResponse.java
  src/main/java/com/ewhatever/qna/user/dto/UserResponse.java
  src/main/java/com/ewhatever/qna/user/entity/User.java
  src/main/java/com/ewhatever/qna/user/service/UserService.java
Labels: ✨ feature, 🛠 fix

#12 [feature/11-postComment] 댓글 등록 API
  src/main/java/com/ewhatever/qna/comment/controller/CommentController.java
  src/main/java/com/ewhatever/qna/comment/dto/CommentRequest.java
  src/main/java/com/ewhatever/qna/comment/dto/PostCommentReq.java
  src/main/java/com/ewhatever/qna/comment/service/CommentService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
Labels: ✨ feature

#13 [feature/10-postQuestion] 질문 등록 API
  .gitignore
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/question/controller/QuestionController.java
  src/main/java/com/ewhatever/qna/question/dto/PostQuestionReq.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
  src/main/resources/application.properties
Labels: ✨ feature

#14 [feature/11-deleteComment] 댓글 삭제 API
  src/main/java/com/ewhatever/qna/comment/controller/CommentController.java
  src/main/java/com/ewhatever/qna/comment/service/CommentService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
Labels: ✨ feature

#15 [feature/3-getPost] 쥬시글 상세 조회 API
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/comment/repository/CommentRepository.java
  src/main/java/com/ewhatever/qna/comment/service/CommentService.java
  src/main/java/com/ewhatever/qna/common/Constant.java
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/dto/GetPostRes.java
  src/main/java/com/ewhatever/qna/post/dto/PostResponse.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
  src/main/java/com/ewhatever/qna/scrap/repository/ScrapRepository.java
Labels: ✨ feature

#16 [feature/3-scrapPost] 쥬시글 스크랩/취소 API
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
  src/main/java/com/ewhatever/qna/scrap/repository/ScrapRepository.java
  src/main/java/com/ewhatever/qna/user/repository/UserRepository.java
Labels: ✨ feature

#17 [feature/11-updateComment] 댓글 수정 API
  src/main/java/com/ewhatever/qna/comment/controller/CommentController.java
  src/main/java/com/ewhatever/qna/comment/dto/UpdateCommentReq.java
  src/main/java/com/ewhatever/qna/comment/entity/Comment.java
  src/main/java/com/ewhatever/qna/comment/service/CommentService.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
Labels: ✨ feature

#18 [fix/3-scrapPost] 쥬시글 스크랩/취소 API 수정
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
Labels: 🛠 fix

#19 [fix/3-getPosts] 쥬시글 목록 조회 API 수정-쥬시글 여부 조건 추가 및 예외 처리
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
Labels: ✨ feature

#20 [feature/10-getQuestions] 질문 목록 조회 API
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/controller/QuestionController.java
  src/main/java/com/ewhatever/qna/question/dto/GetQuestionsRes.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
Labels: ✨ feature

#21 [fix/3-getPosts] 쥬시글 목록 조회 API-검색 추가
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
Labels: ✨ feature, 🛠 fix

#22 [fix/11-postComment] 댓글 등록 API 수정-validation 수정 및 auditing 적용
  src/main/java/com/ewhatever/qna/QnaApplication.java
  src/main/java/com/ewhatever/qna/answer/entity/Answer.java
  src/main/java/com/ewhatever/qna/comment/entity/Comment.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
  src/main/java/com/ewhatever/qna/scrap/entity/Scrap.java
  src/main/java/com/ewhatever/qna/user/entity/User.java
Labels: 🛠 fix

#23 [fix/6-postAnswer] 3번째 답변 등록 시 쥬시글로 전환
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
Labels: 🛠 fix

#24 [fix/4-getMyPage] 마이페이지 조회 API 수정-정렬기준, 목록 내용 글자수 수정
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/user/dto/GetCommentResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetJunyQuestionResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetScrapResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyAnswerResponse.java
  src/main/java/com/ewhatever/qna/user/service/UserService.java
Labels: 🛠 fix

#25 [fix/6-postAnswer] count 메소드 재정의
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
Labels: 🛠 fix

#27 [fix/3-getPost] 쥬시글 상세 조회 commentIdx 반환값 추가
  src/main/java/com/ewhatever/qna/answer/controller/AnswerController.java
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/comment/repository/CommentRepository.java
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/dto/GetPostRes.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/controller/QuestionController.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
Labels: 🛠 fix

#29 [fix/3-getLists] 목록 조회 최신순 수정
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/comment/repository/CommentRepository.java
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
Labels: 🛠 fix

#30 [feature/5-login] 소셜로그인 API 추가
  build.gradle
  src/main/java/com/ewhatever/qna/answer/controller/AnswerController.java
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/comment/controller/CommentController.java
  src/main/java/com/ewhatever/qna/comment/service/CommentService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/common/config/WebConfiguration.java
  src/main/java/com/ewhatever/qna/common/enums/Role.java
  src/main/java/com/ewhatever/qna/login/JwtAuthProvider.java
  src/main/java/com/ewhatever/qna/login/JwtFilter.java
  src/main/java/com/ewhatever/qna/login/JwtIssuer.java
  src/main/java/com/ewhatever/qna/login/controller/LoginController.java
  src/main/java/com/ewhatever/qna/login/dto/AuthService.java
  src/main/java/com/ewhatever/qna/login/dto/GetNaverProfileRes.java
  src/main/java/com/ewhatever/qna/login/dto/JwtTokenDto.java
  src/main/java/com/ewhatever/qna/login/dto/LoginRes.java
  src/main/java/com/ewhatever/qna/login/dto/NaverTokenDto.java
  src/main/java/com/ewhatever/qna/login/dto/UserInfoDto.java
  src/main/java/com/ewhatever/qna/login/service/LoginService.java
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/controller/QuestionController.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
  src/main/java/com/ewhatever/qna/user/controller/UserController.java
  src/main/java/com/ewhatever/qna/user/entity/User.java
  src/main/java/com/ewhatever/qna/user/repository/UserRepository.java
  src/main/java/com/ewhatever/qna/user/service/UserService.java
Labels: ✨ feature

#31 [fix/timeFormat] 날짜 및 시간 반환 형식 변경
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/ewhatever/qna/post/dto/GetPostRes.java
  src/main/java/com/ewhatever/qna/post/dto/GetPostsRes.java
  src/main/java/com/ewhatever/qna/question/dto/GetQuestionsRes.java
Labels: 🛠 fix

#32 [fix/1-setting2] column명, column size 수정
  src/main/java/com/ewhatever/qna/answer/entity/Answer.java
  src/main/java/com/ewhatever/qna/comment/entity/Comment.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
Labels: 🛠 fix

#33 [fix/4-getMyPage2] 카테고리 한글 반환 및 날짜 포맷 변경
  src/main/java/com/ewhatever/qna/common/enums/Category.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
  src/main/java/com/ewhatever/qna/user/dto/GetCommentResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetJunyQuestionResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetScrapResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyAnswerResponse.java
Labels: 🛠 fix

#34 [fix/3-gePosts2] 쥬시글 목록 조회-postIdx 반환값 추가
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
  src/main/java/com/ewhatever/qna/post/dto/GetPostsRes.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
Labels: 🛠 fix

#35 [fix/4-getMyPage3] 내 질문/답변 조회시 postIdx 필드 추가
  src/main/java/com/ewhatever/qna/user/dto/GetJunyQuestionResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyAnswerResponse.java
Labels: 🛠 fix

#36 [fix/modifyResponse] 질문 목록 조회-postIdx 반환값 추가
  src/main/java/com/ewhatever/qna/answer/dto/AnswerResponse.java
  src/main/java/com/ewhatever/qna/question/controller/QuestionController.java
  src/main/java/com/ewhatever/qna/question/dto/GetQuestionsRes.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
Labels: 🛠 fix

#37 [fix/1-setting3] gradle 배포 추가
  .gitignore
  README.md
  build.gradle
Labels: ⚙ infra, 🛠 fix

#38 [] application.properties cache 삭제
  .gitignore
  src/main/resources/application.properties
Labels: ⚙ infra, 🛠 fix

#39 [fix/28-corsSetting] CORS 설정-프론트 배포 url 허용
  src/main/java/com/ewhatever/qna/common/config/WebConfiguration.java
Labels: 🛠 fix

#40 [fix/setting] @RequestMapping 한글 깨짐 해결
  src/main/java/com/ewhatever/qna/post/controller/PostController.java
Labels: 🛠 fix

#41 [fix/4-getMyPage4] 역할 권한 예외 처리 및 일부 내용 반환시 ... 추가
  src/main/java/com/ewhatever/qna/user/dto/GetCommentResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetJunyQuestionResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetScrapResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyAnswerResponse.java
  src/main/java/com/ewhatever/qna/user/service/UserService.java
Labels: 🛠 fix

#42 [fix/4-getMyPage5] 마이페이지 목록 내용 글자수 수정
  src/main/java/com/ewhatever/qna/user/dto/GetCommentResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetJunyQuestionResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetScrapResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyAnswerResponse.java
Labels: 🛠 fix

#44 [fix/dateTime] comment, answers 조회 시 날짜 기준 재설정
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/comment/repository/CommentRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
Labels: 🛠 fix

#46 [feature/45-httpsSetting] http 상태검사 API
  src/main/java/com/ewhatever/qna/login/controller/LoginController.java
Labels: ✨ feature

#47 [fix/3-getPost3] 댓글 작성자 쥬니/시니 구분 수정
  src/main/java/com/ewhatever/qna/common/Constant.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
Labels: 🛠 fix

#48 [fix/3-getPosts3] 댓글 정렬 기준 수정
  src/main/java/com/ewhatever/qna/comment/repository/CommentRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
Labels: 🛠 fix

#49 [fix/3-getPosts4] 쥬시글 등록 날짜 변경 문제 해결
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/post/entity/Post.java
  src/main/java/com/ewhatever/qna/post/repository/PostRepository.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/user/dto/GetJunyQuestionResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetScrapResponse.java
  src/main/java/com/ewhatever/qna/user/dto/GetSinyAnswerResponse.java
Labels: 🛠 fix

#50 [fix/10-postQuestion] 질문 등록 시 제목, 상세 내용 글자수 예외 처리
  src/main/java/com/ewhatever/qna/answer/controller/AnswerController.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
Labels: 🛠 fix

#51 [fix/4-getMyPage6] 쥬시 완료, 쥬시 대기 목록 정렬 수정
  src/main/java/com/ewhatever/qna/user/service/UserService.java
Labels: 🛠 fix

#52 [fix/11-postComment2] 댓글 글자수 예외 처리
  src/main/java/com/ewhatever/qna/comment/entity/Comment.java
  src/main/java/com/ewhatever/qna/comment/service/CommentService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
Labels: 🛠 fix

#53 [fix/5-login3] jwt 토큰 만료시간 수정
  src/main/java/com/ewhatever/qna/login/JwtIssuer.java
Labels: 🛠 fix

#54 [chore/modifyEnumType] Entity enum type 수정
  src/main/java/com/ewhatever/qna/post/entity/Post.java
  src/main/java/com/ewhatever/qna/user/entity/User.java
Labels: 🛠 fix

#57 [feature/56-sendMail] 쥬스레터 발송 API
  build.gradle
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/mail/MailController.java
  src/main/java/com/ewhatever/qna/mail/dto/MailDto.java
  src/main/java/com/ewhatever/qna/mail/service/MailService.java
  src/main/resources/templates/juiceLetter.html
Labels: ✨ feature

#58 [fix/10-getQuestions] 이미 답변한 질문 제외 목록 조회
  src/main/java/com/ewhatever/qna/answer/repository/AnswerRepository.java
  src/main/java/com/ewhatever/qna/answer/service/AnswerService.java
  src/main/java/com/ewhatever/qna/common/Base/BaseResponseStatus.java
  src/main/java/com/ewhatever/qna/post/service/PostService.java
  src/main/java/com/ewhatever/qna/question/controller/QuestionController.java
  src/main/java/com/ewhatever/qna/question/service/QuestionService.java
Labels: 🛠 fix
